---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:d4n13lbc/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: d4n13lbc/podinfo
      tag: dev-deneih4h
    replicaCount: 1
    hpa:
      enabled: false
